{
 "title": "jvm-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "cache-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"cache-service\"}) without(area, id,job)"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"cache-service\"}) without(job)"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"cache-service\", uri!=\"/actuator/prometheus/\"}) without(exception, method, outcome, status, uri,job)"
    }
   ]
  },
  { "title": "websocket-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"websocket-service\"}) without(area, id,job)"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"websocket-service\"}) without(job)"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"websocket-service\", uri!=\"/actuator/prometheus/\"}) without(exception, method, outcome, status, uri,job)"
    }
   ]
  },
  {
   "title": "management-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"management-rest-service\"}) without(area, id, job, application)"
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{job=\"management-rest-service\"}) without(job,application)"
      }
     ]
    },
    {
     "title": "Request/sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 15, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{job=\"management-rest-service\", uri!=\"/actuator/prometheus/\"}) without(exception, method, outcome, status, uri,job,application)"
      }
     ]
    }
   ]
  },
  { "title": "route-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"route-service\"}) without(area, id, job, application)"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"route-service\"}) without(job,application)"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"route-service\", uri!=\"/actuator/prometheus/\"}) without(exception, method, outcome, status, uri,job,application)"
    }
   ]
  }
 ]
}